app:
  port: 8194
  debug: false
  key: dify-sandbox
max_workers: 4
max_requests: 50
worker_timeout: 15
python_path: /usr/local/bin/python3
python_lib_path:
  - /usr/local/lib/python3.10
  - /usr/lib/python3.10
  - /usr/lib/python3
nodejs_path: /usr/local/bin/node
enable_network: true
proxy:
  socks5: ''
  http: 'http://ssrf_proxy:3128'
  https: 'http://ssrf_proxy:3128'
